//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductBlog.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int ProductID { get; set; }
        [Required]
        [StringLength(450)]
        public string ProductName { get; set; }
        [Required]
        public string SKU { get; set; }
        [Required]
        public decimal Price { get; set; }
        public byte[] ImageData { get; set; }
        public Nullable<int> ImageMimeType { get; set; }
        public byte[] ImageThumbnail { get; set; }
        public bool AttachmentsAvailable { get; set; }
    }
}
